const PrivacyPolicy = () => {
    return (
        <div className="font-sui py-8 bg-gray-200">
            <div className="max-w-4xl mx-auto bg-white p-8 shadow-md rounded-lg">
                <h1 className="text-center text-4xl font-[500] mb-4 text-gray-800">Privacy Policy for BRC</h1>
                <p className="text-center text-base text-gray-500 mb-6">Last updated: September 27, 2024</p>
                
                <p className="text-gray-700 mb-4">
                    This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>
                <p className="text-gray-700 mb-4">
                    We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                </p>

                <h2 className="text-2xl font-[500] text-gray-800 mt-8 mb-4">Interpretation and Definitions</h2>
                <h3 className="text-xl font-[500] text-gray-800 mb-2">Interpretation</h3>
                <p className="text-gray-700 mb-4">
                    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>

                <h3 className="text-xl font-[500] text-gray-800 mb-2">Definitions</h3>
                <ul className="list-disc pl-5 text-gray-700 mb-4">
                    <li><strong>Account</strong>: a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong>Affiliate</strong>: an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of shares, equity interest, or other securities.</li>
                    <li><strong>Company</strong>: refers to 4852N PTE LTD, 10 Anson Road, #22-02 International Plaza, Singapore 79903.</li>
                    <li><strong>Cookies</strong>: small files placed on Your device by a website, containing details of Your browsing history on that website.</li>
                    <li><strong>Country</strong>: refers to Singapore.</li>
                    <li><strong>Device</strong>: any device that can access the Service, like a computer, cellphone, or digital tablet.</li>
                    <li><strong>Personal Data</strong>: information relating to an identified or identifiable individual.</li>
                    <li><strong>Service</strong>: refers to the Website.</li>
                    <li><strong>Service Provider</strong>: any person or entity that processes data on behalf of the Company.</li>
                    <li><strong>Usage Data</strong>: data collected automatically, generated by the use of the Service or its infrastructure.</li>
                    <li><strong>Website</strong>: refers to BRC, accessible from battleroyalechampionship.com.</li>
                    <li><strong>You</strong>: the individual accessing or using the Service, or the company on behalf of which they do so.</li>
                </ul>

                <h2 className="text-2xl font-[500] text-gray-800 mt-8 mb-4">Collecting and Using Your Personal Data</h2>
                <h3 className="text-xl font-[500] text-gray-800 mb-2">Types of Data Collected</h3>
                <h4 className="text-md font-[500] text-gray-800 mb-2">Personal Data</h4>
                <p className="text-gray-700 mb-4">
                    We may ask You to provide Us with personally identifiable information for contact or identification purposes, including:
                </p>
                <ul className="list-disc pl-5 text-gray-700 mb-4">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                </ul>

                <h4 className="text-md font-[500] text-gray-800 mb-2">Usage Data</h4>
                <p className="text-gray-700 mb-4">
                    Usage Data may include information such as Your IP address, browser type and version, pages visited, time and date of visits, time spent on pages, unique device identifiers, and other diagnostic data.
                </p>

                <h2 className="text-2xl font-[500] text-gray-800 mt-8 mb-4">Tracking Technologies and Cookies</h2>
                <p className="text-gray-700 mb-4">
                    We use Cookies and similar tracking technologies to track activity on Our Service and store certain information, using beacons, tags, and scripts for data collection and analysis.
                </p>

                <h3 className="text-xl font-[500] text-gray-800 mb-2">Use of Your Personal Data</h3>
                <p className="text-gray-700 mb-4">
                    The Company may use Personal Data to:
                </p>
                <ul className="list-disc pl-5 text-gray-700 mb-4">
                    <li>Provide and maintain our Service, including usage monitoring.</li>
                    <li>Manage Your registration as a user of the Service.</li>
                    <li>Contact You via email, phone calls, SMS, or other communication forms.</li>
                    <li>Provide updates, offers, and information about other goods, services, and events.</li>
                </ul>

                <h2 className="text-2xl font-[500] text-gray-800 mt-8 mb-4">Retention of Your Personal Data</h2>
                <p className="text-gray-700 mb-4">
                    We retain Your Personal Data only as long as necessary for the purposes stated in this Privacy Policy.
                </p>

                <h2 className="text-2xl font-[500] text-gray-800 mt-8 mb-4">Security of Your Personal Data</h2>
                <p className="text-gray-700 mb-4">
                    We prioritize the security of Your Personal Data, though no internet transmission or electronic storage is 100% secure.
                </p>

                <h2 className="text-2xl font-[500] text-gray-800 mt-8 mb-4">Children's Privacy</h2>
                <p className="text-gray-700 mb-4">
                    Our Service does not address anyone under 13. We do not knowingly collect data from anyone under 13.
                </p>

                <h2 className="text-2xl font-[500] text-gray-800 mt-8 mb-4">Links to Other Websites</h2>
                <p className="text-gray-700 mb-4">
                    Our Service may contain links to external sites not operated by Us. Upon clicking a third-party link, You will be directed to that third party's site.
                </p>

                <h2 className="text-2xl font-[500] text-gray-800 mt-8 mb-4">Changes to this Privacy Policy</h2>
                <p className="text-gray-700 mb-4">
                    We may update Our Privacy Policy periodically and will notify You of any changes via this page.
                </p>

                <h2 className="text-2xl font-[500] text-gray-800 mt-8 mb-4">Contact Us</h2>
                <p className="text-gray-700">
                    If you have any questions, contact us via email at: <a href="mailto:contact@battleroyalechampionship.com" className="text-blue-600 hover:underline">contact@battleroyalechampionship.com</a>
                </p>
            </div>
        </div>
    );
};

export default PrivacyPolicy;
